# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#   - board: nice_nano
#     shield: corne_left
#     snippet: studio-rpc-usb-uart
#     cmake-args: -DCONFIG_ZMK_STUDIO=y
#     artifact-name: corne_left_with_studio
#

# github.com/srwi/keypeek
# added raw_hid_adapter shield for nice_nano_v2 to support the Raw HID module, which is a dependency of the KeyPeek module
---
include:
  - board: nice_nano_v2
    shield: lily58_left raw_hid_adapter
    # added studio-rpc-usb-uart snippet for the left half of the Lily58 to support the KeyPeek module, which is a dependency of the KeyPeek Layer Notifier module
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: lily58_right
